### ISSUE TITLE
No response body for missed pickups endpoint

### ISSUE THREAD

**Issue by mbs-zanas-stundys** [mbs-zanas-stundys/hack4vilnius-2019#18]
![image](https://user-images.githubusercontent.com/41042117/67597825-b6674900-f774-11e9-83e1-7c48e62b9177.png)
![image](https://user-images.githubusercontent.com/41042117/67597844-cb43dc80-f774-11e9-9a75-e5d41b239ed1.png)

**Comment by mbs-zanas-stundys** [comment]
I fixed the query. Now the request is sent to the correct endpoint. Nonetheless, there's no results regardless of what `date` parameter is passed.

**Comment by DonatasZu** [comment]
![image](https://user-images.githubusercontent.com/48481743/67618660-e6592f80-f7fa-11e9-9e49-d70956114dea.png)
Date is not required. by default current date will be passed

**Comment by mbs-zanas-stundys** [comment]
Still there's no result being returned. I cleaned the mongodb, re-imported all the data and still `containers/pickup` always returns an empty array. Here's a snapshot of mongodb:
![image](https://user-images.githubusercontent.com/41042117/67624975-a7e66380-f840-11e9-869b-abc93a430c90.png)
