### ISSUE TITLE
GET /containers/{containerNo}/history expects a request body

### ISSUE THREAD

**Issue by mbs-zanas-stundys** [mbs-zanas-stundys/hack4vilnius-2019#19]
`date` is expected as a request body. Maybe it should've been a query parameter?
![image](https://user-images.githubusercontent.com/41042117/67598380-11e60680-f776-11e9-99d0-16c7689039b0.png)
![image](https://user-images.githubusercontent.com/41042117/67598396-17435100-f776-11e9-8f90-40661c16868b.png)

**Comment by DonatasZu** [comment]
Fixed annotation. Date will be optional request parameter. If not passed by default current day will be used
